### ISSUE TITLE
The animal dissapear 

### ISSUE THREAD

**Issue by medalofbofo** [MarkusBordihn/BOs-Player-Companions#11]
when I tame an animal from the mod it disappears nothing appears in my inventory

I have the 1.18.2 version i put this mod in my private server.

Hope you can help me.

Thanks!

**Comment by MarkusBordihn** [comment]
Could you please post a link with your `logs/latest.log` file.
The mod check, if it was able to put something in the inventory and if not it will just drop the item to the world instead.
But this should be visible in the log file to give me a hint what is not working in your case.
