### ISSUE TITLE
when companions are clicked with their respective item they just dissapear 1.18.2

### ISSUE THREAD

**Issue by GreenForzeGaming** [MarkusBordihn/BOs-Player-Companions#13]

**Comment by MarkusBordihn** [comment]
Please provide more details to this report, at least you should provide the following:

- [ ] Steps to reproduce the issue ?
- [ ] A link to your `latest.log` log file ?
- [ ] The used Minecraft client and mods, if not already included in your `latest.log` ?
- [ ] Your `world/data/player_companions.data` for this specific issue.

**Comment by GreenForzeGaming** [comment]
step one : use tame item on the companion

step two : it sayes i claimed a rooster, though its no where too be found.

[07Nov2022 22:16:38.308] [Server thread/INFO] [Bo's Player Companions/]: Player ServerPlayer['Dois'/243447, l='ServerLevel[Infiniti Craft]', x=755.03, y=67.00, z=580.52] tamed player companion Rooster['Larry'/345870, l='ServerLevel[Infiniti Craft]', x=755.39, y=67.00, z=581.97, tamed=true, owner='67b5072b-ca5a-43e4-8193-fc58bf8ab1a2'] ...
[07Nov2022 22:16:38.308] [Server thread/INFO] [Bo's Player Companions/]: Register companion Rooster['Larry'/345870, l='ServerLevel[Infiniti Craft]', x=755.39, y=67.00, z=581.97, tamed=true, owner='67b5072b-ca5a-43e4-8193-fc58bf8ab1a2'] for ServerPlayer['Dois'/243447, l='ServerLevel[Infiniti Craft]', x=755.03, y=67.00, z=580.52] ...
[07Nov2022 22:16:38.310] [Server thread/INFO] [Bo's Player Companions/]: Gave player ServerPlayer['Dois'/243447, l='ServerLevel[Infiniti Craft]', x=755.03, y=67.00, z=580.52] captured companion item with rooster_mixed.
[07Nov2022 22:16:56.963] [Server thread/INFO] [Bo's Player Companions/]: 👾 Bo's Player Companions saving data ... de.markusbordihn.playercompanions.data.PlayerCompanionsServerData@24590d7

step three : 
	Mod List: 
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  
|DONE      |Manifest: NOSIGNATURE
		habitat-1.1.4.jar                                 |Habitat                       |habitat                       |1.1.4               
|DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.18.2-Forge-1.0.1  
|DONE      |Manifest: NOSIGNATURE
		reeves-furniture-1.18.2-0.8r.jar                  |Reeves Furniture              |reevesfurniture               |0.8                 
|DONE      |Manifest: NOSIGNATURE
		beautify-1.18.2-1.4.0.jar                         |Beautify                      |beautify                      |1.4.0               
|DONE      |Manifest: NOSIGNATURE
		upsizer-mc1.18.2-7.0a1.jar                        |Upsizer                       |upsizer                       |7.0a1               
|DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.18.2-Forge-1.0.3.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.18.2-Forge-1.0.3  
|DONE      |Manifest: NOSIGNATURE
		dynamiclights-1.18.6.jar                          |Dynamic Lights                |dynamiclights                 |1.18.6              
|DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.13.132.jar           |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.13.132   |DONE      |Manifest: NOSIGNATURE
		nyfsquiver-1.18.2-0.7.3.jar                       |Nyf's Quiver                  |nyfsquiver                    |1.18.1-0.7.0        
|DONE      |Manifest: NOSIGNATURE
		InsaneLib-1.5.1-mc1.18.2.jar                      |InsaneLib                     |insanelib                     |1.5.1               
|DONE      |Manifest: NOSIGNATURE
		Apple+Crates-forge-1.18.2-1.7.3.jar               |Apple Crates                  |applecrates                   |1.7.3               
|DONE      |Manifest: NOSIGNATURE
		heartcrystal.jar                                  |Heart Crystal                 |heartcrystal                  |1.0.0               
|DONE      |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.1.1.jar      |CookingForBlockheads          |cookingforblockheads          |12.1.1              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.2-6.6.6.jar                          |Placebo                       |placebo                       |6.6.6               
|DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.2.6.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.2.6  
|DONE      |Manifest: NOSIGNATURE
		premium_wood-1.18.2-1.3.7.jar                     |Premium Wood                  |premium_wood                  |1.3.7               |DONE      |Manifest: NOSIGNATURE
		GatewaysToEternity-1.18.2-2.1.3.jar               |Gateways To Eternity          |gateways                      |2.1.3              
|DONE      |Manifest: NOSIGNATURE
		wildbackport-1.2.3.jar                            |TheWildBackport               |wildbackport                  |1.2.3               
|DONE      |Manifest: NOSIGNATURE
		itemzoom-1.18.2-2.6.0.jar                         |Item Zoom                     |itemzoom                      |2.6.0               
|DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.18.29.718.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.29.718  
|DONE      |Manifest: NOSIGNATURE
		simpleplanes-1.18.2-4.15.0.jar                    |Simple Planes                 |simpleplanes                  |1.18.2-4.15.0       
|DONE      |Manifest: NOSIGNATURE
		Apotheosis-1.18.2-5.7.5.jar                       |Apotheosis                    |apotheosis                    |5.7.5               
|DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.7-mc1.18.2.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.7               
|DONE      |Manifest: NOSIGNATURE
		magicaljewelry-1.18.2_1.4.2.jar                   |Magical Jewelry               |magicaljewelry                |1.18.2_1.4.2        
|DONE      |Manifest: NOSIGNATURE
		balm-3.2.0+0.jar                                  |Balm                          |balm                          |3.2.0+0             
|DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
		KnightQuest1.0.9.TheGatesUpdatePartII.jar         |Knight Quest                  |knight_quest                  |1.0.9               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              
|DONE      |Manifest: NOSIGNATURE
		stackrefill_1.18.2-3.2.jar                        |Stack Refill                  |stackrefill                   |3.2                 
|DONE      |Manifest: NOSIGNATURE
		shetiphiancore-1.18-3.10.10.jar                   |ShetiPhian-Core               |shetiphiancore                |3.10.10             
|DONE      |Manifest: NOSIGNATURE
		dragonmounts-1.18.2-1.1.4.jar                     |Dragon Mounts: Legacy         |dragonmounts                  |1.1.4               |DONE      |Manifest: NOSIGNATURE
		PathToDirt-1.4.2-mc1.18.2.jar                     |Path To Dirt                  |pathtodirt                    |1.4.2               
|DONE      |Manifest: NOSIGNATURE
		konkrete_forge_1.5.3_MC_1.18-1.18.2.jar           |Konkrete                      |konkrete                      |1.5.3               
|DONE      |Manifest: NOSIGNATURE
		structure_gel-1.18.2-2.4.7.jar                    |Structure Gel API             |structure_gel                 |2.4.7               
|DONE      |Manifest: NOSIGNATURE
		corpse-1.18.2-1.0.1.jar                           |Corpse                        |corpse                        |1.18.2-1.0.1        
|DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.0        
|DONE      |Manifest: NOSIGNATURE
		customizableelytra-1.18.2-1.6.5.jar               |Customizable Elytra           |customizableelytra            |1.18.2-1.6.5        |DONE      |Manifest: NOSIGNATURE
		torchmaster-18.1.0.jar                            |Torchmaster                   |torchmaster                   |18.1.0              
|DONE      |Manifest: NOSIGNATURE
		tempad-forge-1.18.2-1.4.1.jar                     |Tempad                        |tempad                        |1.4.1               
|DONE      |Manifest: NOSIGNATURE
		verdure-1.18.2-1.1.2.jar                          |Verdure                       |verdure                       |1.1.2               
|DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.18.2-1.2.0.jar                    |Dungeons Plus                 |dungeons_plus                 |1.2.0               
|DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.6-mc1.18.2.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |DONE      |Manifest: NOSIGNATURE
		dungeons_enhanced-1.18.2-3.2.1.jar                |Dungeons Enhanced             |dungeons_enhanced             |3.2.1               |DONE      |Manifest: NOSIGNATURE
		trofers-1.18.2-2.7.0.jar                          |Trofers                       |trofers                       |1.18.2-2.7.0        
|DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      
|DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         
|DONE      |Manifest: NOSIGNATURE
		corail_woodcutter-1.18.2-2.3.7.jar                |Corail Woodcutter             |corail_woodcutter             |2.3.7               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-5.11.jar                        |Collective                    |collective                    |5.11                
|DONE      |Manifest: NOSIGNATURE
		advancednetherite-1.14.0-1.18.2.jar               |Advanced Netherite            |advancednetherite             |1.14.0              |DONE      |Manifest: NOSIGNATURE
		spyglass_improvements-1.2+mc1.18.x+forge.jar      |Spyglass Improvements         |spyglass_improvements         |1.2+mc1.18.x        |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-5.8.0.jar                            |FramedBlocks                  |framedblocks                  |5.8.0               
|DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.18.2-Forge-2.1.1  
|DONE      |Manifest: NOSIGNATURE
		constructionwand-1.18.2-2.7.jar                   |Construction Wand             |constructionwand              |1.18.2-2.7          |DONE      |Manifest: NOSIGNATURE
		architectury-4.9.84-forge.jar                     |Architectury                  |architectury                  |4.9.84              
|DONE      |Manifest: NOSIGNATURE
		curiouselytra-forge-1.18.1-5.0.1.0.jar            |Curious Elytra                |curiouselytra                 |1.18.1-5.0.1.0      
|DONE      |Manifest: NOSIGNATURE
		moreoverlays-1.20.9-mc1.18.2.jar                  |More Overlays Updated         |moreoverlays                  |1.20.9-mc1.18.2     |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.18.2-2.7.3.jar                  |Majrusz Library               |majruszlib                    |2.7.3               
|DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.2.2-forge-mc1.18.jar               |Chunk Loaders                 |chunkloaders                  |1.2.2               |DONE      |Manifest: NOSIGNATURE
		MobCatcher-Forge-1.18.2-1.1.5.jar                 |Mob Catcher                   |mob_catcher                   |1.1.5               
|DONE      |Manifest: NOSIGNATURE
		framework-0.2.4-1.18.2.jar                        |Framework                     |framework                     |0.2.4               
|DONE      |Manifest: NOSIGNATURE
		smallships-1.18.2-2.0.0-Alpha-0.4.jar             |Small Ships Mod               |smallships                    |2.0.0-a0.4          
|DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-28.jar                              |FastLeafDecay                 |fastleafdecay                 |28                  
|DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.18.2-Forge-2.2.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.18.2-Forge-2.2    
|DONE      |Manifest: NOSIGNATURE
		voidtotem-forge-1.18.2-1.3.1.jar                  |Void Totem                    |voidtotem                     |1.18.2-1.3.1        
|DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.18.2-0.20.jar                  |Vein Mining                   |veinmining                    |1.18.2-0.20         
|DONE      |Manifest: NOSIGNATURE
		PlayerRevive_FORGE_v2.0.12_mc1.18.2.jar           |PlayerRevive                  |playerrevive                  |2.0.12              
|DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v3.3.3-1.18.2-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |3.3.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BorderlessWindow-1.18-1.4.0.jar                   |Borderless Window             |borderlesswindow              |1.18-1.4.0          |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.30.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.30              
|DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.45.jar                    |GeckoLib                      |geckolib3                     |3.0.45              
|DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.18.1-11.0.2.jar                 |TrashSlot                     |trashslot                     |11.0.2              
|DONE      |Manifest: NOSIGNATURE
		cgm-1.2.7-1.18.2.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.7               
|DONE      |Manifest: NOSIGNATURE
		biomesinjars_forge_1.1.1_MC_1.18.2.jar            |Biomes in Jars                |biomesinjars                  |1.1.1               
|DONE      |Manifest: NOSIGNATURE
		sophisticatedstorage-1.18.2-0.5.17.152.jar        |Sophisticated Storage         |sophisticatedstorage          |1.18.2-0.5.17.152   
|DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           
|DONE      |Manifest: NOSIGNATURE
		JEIEnchantmentInfo-1.17.1-2.0.0.jar               |JEI Enchantment Info          |jeienchantmentinfo            |1.17.1-2.0.0        |DONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v3.3.0-1.18.2-Forge.jar           |Visual Workbench              |visualworkbench               |3.3.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      
|DONE      |Manifest: NOSIGNATURE
		sootychimneys-0.6.0.jar                           |Sooty Chimneys                |sootychimneys                 |0.6.0               
|DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+15.jar                  |Clumps                        |clumps                        |8.0.0+15            
|DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.5.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.5      
|DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.7-forge  
|DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.2-4.2.0.jar                        |Artifacts                     |artifacts                     |1.18.2-4.2.0        
|DONE      |Manifest: NOSIGNATURE
		Decorative+Blocks-forge-1.18.2-2.1.2.jar          |Decorative Blocks             |decorative_blocks             |2.1.2               |DONE      |Manifest: NOSIGNATURE
		champions-forge-1.18.2-2.1.6.0.jar                |Champions                     |champions                     |1.18.2-2.1.6.0      |DONE      |Manifest: NOSIGNATURE
		simplekiln-1.18.2-0.0.1.jar                       |Simple Kiln                   |simplekiln                    |1.18.2-0.0.1        
|DONE      |Manifest: NOSIGNATURE
		everycomp-1.18.2-1.5.12.jar                       |Every Compat                  |everycomp                     |1.18.2-1.5.12       
|DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.18.2-Forge-1.3.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.18.2-Forge-1.3.1  
|DONE      |Manifest: NOSIGNATURE
		JEITweaker-1.18.2-3.0.0.9.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.9             
|DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.5.0.jar                        |Blueprint                     |blueprint                     |5.5.0               
|DONE      |Manifest: NOSIGNATURE
		savage_and_ravage-1.18.2-4.0.0.jar                |Savage & Ravage               |savage_and_ravage             |4.0.0               |DONE      |Manifest: NOSIGNATURE
		incubation-1.18.2-2.0.2.jar                       |Incubation                    |incubation                    |2.0.2               
|DONE      |Manifest: NOSIGNATURE
		DisplayCase-forge-1.18.2-1.0.3.jar                |Display Case Mod              |display_case                  |1.0.3              
|DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.196.jar             |CraftTweaker                  |crafttweaker                  |9.1.196             
|DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.18.2-2.7.9.jar                      |Ars Nouveau                   |ars_nouveau                   |2.7.9               
|DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.84-universal.jar                |Forge                         |forge                         |40.1.84            
|DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       
|DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.12.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.12       |DONE      |Manifest: NOSIGNATURE
		AxesAreWeapons-1.6.0-forge-1.18.2.jar             |Axes Are Weapons              |axesareweapons                |1.6.0               |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-7.0.3-forge-mc1.18.2.jar             |Antique Atlas                 |antiqueatlas                  |7.0.3-forge-mc1.18.2
|DONE      |Manifest: NOSIGNATURE
		craftingtweaks-forge-1.18.2-14.0.3.jar            |CraftingTweaks                |craftingtweaks                |14.0.3              
|DONE      |Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              
|DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           
|DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21 (1).jar             |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		EasierSleeping-1.18.2-2.1.0.jar                   |Easier Sleeping               |easier_sleeping               |2.1.0               
|DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.4.jar                       |Jade                          |jade                          |5.2.4               
|DONE      |Manifest: NOSIGNATURE
		inventorytotem_1.18.2-1.6.jar                     |Inventory Totem               |inventorytotem                |1.6                 
|DONE      |Manifest: NOSIGNATURE
		another_furniture-forge-1.2.2-1.18.2.jar          |Another Furniture             |another_furniture             |1.2.2-1.18.2        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.15_mc1.18.2.jar           |CreativeCore                  |creativecore                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		CreateTweaker-1.18.2-2.0.0.17.jar                 |CreateTweaker                 |createtweaker                 |2.0.0.17            
|DONE      |Manifest: NOSIGNATURE
		ambientadditions-1.18.2-0.8.0.jar                 |Ambient Additions             |ambientadditions              |1.18.2-0.8.0        |DONE      |Manifest: NOSIGNATURE
		personality-1.18.2-2.0.0.jar                      |Personality                   |personality                   |2.0.0               
|DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.5.jar                   |Flywheel                      |flywheel                      |0.6.5               
|DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.e.jar                         |Create                        |create                        |0.5.0.e             
|DONE      |Manifest: NOSIGNATURE
		createdeco-1.2.11-1.18.2.jar                      |Create Deco                   |createdeco                    |1.2.11-1.18.2       
|DONE      |Manifest: NOSIGNATURE
		ecologics-forge-1.18.2-1.7.10.jar                 |Ecologics                     |ecologics                     |1.7.10              
|DONE      |Manifest: NOSIGNATURE
		experienceobelisk-v1.3.6-1.18.2.jar               |Experience Obelisk            |experienceobelisk             |1.3.6               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.2-0.45.jar                   |Polymorph                     |polymorph                     |1.18.2-0.45         
|DONE      |Manifest: NOSIGNATURE
		multibeds-1.18-1.9.6.jar                          |Multi-Beds                    |multibeds                     |1.9.6               
|DONE      |Manifest: NOSIGNATURE
		corail_recycler-5.5.1-1.18.2.jar                  |Corail Recycler               |corail_recycler               |5.5.1               
|DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              
|DONE      |Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             
|DONE      |Manifest: NOSIGNATURE
		DramaticDoors-Forge-1.18.2-2.1.3.jar              |Dramatic Doors                |dramaticdoors                 |1.18.2-2.1.3        |DONE      |Manifest: NOSIGNATURE
		DiagonalFences-v3.1.0-1.18.2.jar                  |Diagonal Fences               |diagonalfences                |3.1.0               
|DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		crittersandcompanions-1.18.2-1.0.2.jar            |Critters and Companions       |crittersandcompanions         |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		lapidary-1.2.jar                                  |Lapidary                      |lapidary                      |1.18.2-1.2          
|DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.18].forge-3.4.4.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.4               |DONE      |Manifest: NOSIGNATURE
		effective_fg-1.2.4.jar                            |Effective (Forge)             |effective_fg                  |1.2.4               
|DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-1.18.2-1.3.0-forge.jar            |Creeper Overhaul              |creeperoverhaul               |1.3.0               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      
|DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.3.5-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.5               
|DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Enhanced_Celestials-forge-1.18.2-2.0.7.jar        |Enhanced Celestials           |enhancedcelestials            |2.0.7               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.2-2.3.8.jar                      |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.8        
|DONE      |Manifest: NOSIGNATURE
		majruszs-enchantments-1.18.2-1.6.3.jar            |Majrusz's Enchantments        |majruszsenchantments          |1.6.3               |DONE      |Manifest: NOSIGNATURE
		player_companions_1.18.2-1.6.0.jar                |Bo's Player Companions        |player_companions             |1.6.0               |DONE      |Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               
|DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.2-v2a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		Overloaded+Armor+Bar+6.0.0.jar                    |Overloaded Armor Bar          |overloadedarmorbar            |6.0.0               |DONE      |Manifest: NOSIGNATURE

step four : could not upload NBT

**Comment by MarkusBordihn** [comment]
Thanks for the details. According the logs the issue is related to the used client or one of the inventory related mods.

Could you please let me know the client you are using and testing if you experience the same issue with only this mod without the other?
- If you still getting the same issue with this mod alone, it's related to your client / client version.
- If you are not getting the same issue, it's related to one of the mods in your mod pack,

The mod is using the client function `net.minecraft.world.entity.player.Inventory.add(...)` for adding the item to the inventory.
According your feedback I will check if I could add an additional test for this, but from the technical side and according the log, the mod is working as expected.
