### ISSUE TITLE
Fairy skin changing randomly.

### ISSUE THREAD

**Issue by DanielToledo12** [MarkusBordihn/BOs-Player-Companions#14]
Hello! I've been using your mod for a while now and never had this issue before.

The issue is basically the skin changes when I go to sleep ( in-game ) and when I wake up I find a grown fairy with a new skin (blondie one), it also happens when I capture her to join caves with lots of lava so I wanna keep her safe, and when she is free there is a new skin.

I am attaching some screenshots so you can see an example. Her name is Emma, she is supposed to have black hair but suddenly when I spawned her she is now blonde but keeping the name. I guess it's important to point out she was a baby and was growing up.

![imagen_2022-12-04_000547390](https://user-images.githubusercontent.com/119774754/205475484-017dd26a-9b12-4e1b-8d46-65224ddea459.png)

![imagen_2022-12-04_000632268](https://user-images.githubusercontent.com/119774754/205475509-cdbe09fc-c88c-4b38-8347-c7b8b43ce32c.png)

I've tried like 20 fairies, most of them redhead, before reporting an issue here, but it keeps happening so I just wanted to let you know. Hopefully there is a fix for this.

Thanks in advance 😄

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report and sorry for the late response.
The latest versions includes some fixes for the texture cache and also display the "texture variant" in the player companion screen.

![image](https://user-images.githubusercontent.com/12183293/215915983-64d10a92-089c-49c9-a6f1-370073f74ca0.png)

Please let me know if you still experience these kind of issue and it would be great if you could share the new player companion screen of the effected player companions. Thanks.

**Comment by DanielToledo12** [comment]
Thank you very much for updating the mod, I'll check in the next days, sorry for the late answer hopefully I have more time to try and test it :D
