### ISSUE TITLE
Item disappears after being tamed

### ISSUE THREAD

**Issue by Julianna91** [MarkusBordihn/BOs-Player-Companions#16]
Hi! I think there is a bug because I have tried to tame different creatures, but the item is not even added to my inventory as soon as it is tamed.

I am not the only one with this problem because someone else commented.

The version is 1.19.2 

Thank you!

**Comment by MarkusBordihn** [comment]
Thanks for the report. Could you please attach the corresponding log to be able to check this more in detail.

For most of the reported issues in the past a modified client /server was used, which caused this issues.
I haven't received a valid user report with a official Forge client / CurseForge for such issues so far.
