### ISSUE TITLE
Book doens't work

### ISSUE THREAD

**Issue by DayIsGone** [MarkusBordihn/BOs-Player-Companions#22]
**Describe the bug**
The book will not open. When you click to open it it does nothing the tool tip on it says Invalid book companions guide

**To Reproduce**
1. join world
2. click book
3. it does nothing

**Expected behavior**
The book to open and show the information

**Screenshots**
![guidebook](https://github.com/MarkusBordihn/BOs-Player-Companions/assets/107453692/50ccac8c-7b74-4d56-833e-c48675b4d098)

**Debugging**
the log does say this 
22.07 03:56:20 [Server] modloading-worker-0/ERROR [patchouli/]: Failed to load book player_companions:guide defined by mod player_companions, skipping
22.07 03:56:20 [Server] INFO java.lang.IllegalArgumentException: Book player_companions:guide has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

**Additional context**

**Comment by MarkusBordihn** [comment]
Implementation Reference: https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120/

**Comment by MarkusBordihn** [comment]
Thanks for the report. This is fixed and should be online in the next hour.
