### ISSUE TITLE
Snails spawn on the sea and stay ontop

### ISSUE THREAD

**Issue by GiantCrocodile** [MarkusBordihn/BOs-Player-Companions#23]
Hello,

I just started with latest Forge 47.1.43 and Minecraft 1.20.1 and player_companions_1.20.1-6.0.1.jar. After creating a new map, I can see snails at sand beach in some nowhere but they spawn as well on the sea and stay on top of the sea so basically it looks a bit weird and uncommon. Sounds like a small bug to me.

Best Regards,

**Comment by MarkusBordihn** [comment]
Thanks for the report. Will fix this with the next update.

**Comment by GiantCrocodile** [comment]
Eh wow, that's the quickest update I could have imagined. Thank you for your effort and the great idea of this mod.
