### ISSUE TITLE
Server crash.  Trying to access a sound.

### ISSUE THREAD

**Issue by Plisko1** [MarkusBordihn/BOs-Player-Companions#24]
**Describe the bug**

We have a small 5 player Bisect Hosting server and we have been testing companions recently.  Our players have found several companions and they usually have several out at a time.

The server has crashed several times while testing our modpack.  Chat GPT Analysis of the crash report suggests that Player Companions is related to the crash.

This is what GPT 4 with "code interpreter" said about two server crash reports I had it analyze:

>>>>
The crash is attributed to a "Ticking entity."

Description: Ticking entity
The crash originated from a NullPointerException when trying to invoke a method related to sound events.
java.lang.NullPointerException: Cannot invoke "net.minecraft.sounds.SoundEvent.m_215668_(float)" because the return value of "net.minecraft.core.Holder.m_203334_()" is null

The stack trace also references PlayerCompanionEntityWalkControl from the player_companions mod.

Given this recap, the two crash logs you've shared seem to have the same root cause: an issue with the player_companions mod when entities associated with this mod attempt to play a sound.

Since both crash logs point to the same mod and similar behavior, I would recommend focusing on the player_companions mod to address the issues. This could include updating the mod, checking its configurations, or temporarily removing it for diagnostic purposes.
>>>>

We have grown fond of our companions and we would rather not remove the mod.

**To Reproduce**

Running with companions on our 1.19.3 server till it happens.

**Debugging**
Before reporting a issue please check if there is anything relevant in the crash-reports, debug.log and latest.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

It is a large modpack with 90 mods.  Other than this, I have not seen any evidence of conflicts in various logs I have had analyzed.  The mods are listed in the attached crash report.

**Additional context**

This has happened several times now with similar crash reports.
Please let me know if you need anything else.

[crash-2023-08-08_12.45.49-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12291569/crash-2023-08-08_12.45.49-server.txt)

**Comment by Plisko1** [comment]
Adding the latest log and debug log:
[latest (2).log](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12291632/latest.2.log)
[debug (1).log](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12291633/debug.1.log)

**Comment by Plisko1** [comment]
I also want to add that the log is showing a warning that it detects a modified version of Player companions and not the official curseforge version.  I only ever used the Curseforge version of this mod:  player_companions_1.19.3-6.0.0.jar

**Comment by MarkusBordihn** [comment]
Thanks for the report. According the crash log the wait sound is missing which is used by the Rooster Player Companion and causes this crash.

I just released a quick fix 6.0.1 to ignore empty sounds, please let me know if this fixed the issue for you. Thanks.

**Comment by Plisko1** [comment]
Looks like that did the trick.  We updated and played for a couple of hours with no problems.  Thanks for being so fast!
