### ISSUE TITLE
The entity 'Toni' at the location 12067.56, 63.56, 1491 is causing issues while ticking.

### ISSUE THREAD

**Issue by Rennihold** [MarkusBordihn/BOs-Player-Companions#26]
The entity 'Toni' at the location 12067.56, 63.56, 1491 is causing issues while ticking.

"Toni" is the name from one of the companions, a samurai, it happens also with differents companions constantly every 15-20 minutes

here an example from one of the crashes:
https://pastebin.com/hMdtzSrv

Forge 47.2.0
Minecraft 1.20.1

**Comment by MarkusBordihn** [comment]
Thanks for the report.
Please try the following version, if this fixes the issue:
https://www.curseforge.com/minecraft/mc-mods/player-companions/files/4783810

**Comment by Rennihold** [comment]
i think i should wait more time, but i think i can say that it works, thanks. great mod.
