### ISSUE TITLE
Fairy without waiting sound causing crashes.

### ISSUE THREAD

**Issue by M25R4PTOR** [MarkusBordihn/BOs-Player-Companions#27]
**Describe the bug**
Crash Game Like https://github.com/MarkusBordihn/BOs-Player-Companions/issues/25 but its fairy

**To Reproduce**
1. Open World LAN
2. Fairy friends stay sit
3. Wait and the game crash

**Expected behavior**
No crash xD

**Screenshots**
There is also a small error regarding the baby raptor, when sitting he appears decapitated xD

![2023-10-08_02 57 23](https://github.com/MarkusBordihn/BOs-Player-Companions/assets/32265733/a6e90da2-3744-4b32-94ad-4e8ac2e10694)

**Debugging**
[crash-2023-10-08_02.46.45-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12839522/crash-2023-10-08_02.46.45-server.txt)

**Additional**
The default raptor is a bit bland, if you could add the same details as the pink one it would look much better and adding more variants would be great jeje.

It's a great mod, thanks for everything!

**Comment by M25R4PTOR** [comment]
If you can fix it I can test it this Wednesday night

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report.

I fixed the issue for all versions and replaced all playSound... so this should no longer happen with any companion.
I additionally fixed the baby raptors ^^° and added a new variant which is a mix of the default and the pink one.

**Comment by M25R4PTOR** [comment]
It happened again with the rooster, the samurai, the fairy and the raptor.

**Debugging**
[crash-2023-10-12_03.41.21-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12876675/crash-2023-10-12_03.41.21-server.txt)
[crash-2023-10-12_04.23.46-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12876677/crash-2023-10-12_04.23.46-server.txt)
[crash-2023-10-12_05.05.54-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12876678/crash-2023-10-12_05.05.54-server.txt)
[crash-2023-10-12_05.53.24-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12879619/crash-2023-10-12_05.53.24-server.txt)
