### ISSUE TITLE
Mobs without waiting sound causing crashes.

### ISSUE THREAD

**Issue by M25R4PTOR** [MarkusBordihn/BOs-Player-Companions#28]
**Describe the bug**
Crash Game Like https://github.com/MarkusBordihn/BOs-Player-Companions/issues/27 but its rooster, samurai, fairy and raptor.
I used version player_companions_1.20.1-6.6.2

**To Reproduce**
1. Open World LAN
2. Mobs friends stay sit
3. Wait and the game crash

**Expected behavior**
No crash xD

**Debugging**
Server(SinglePlayer Open World Lan) logs: 
[crash-2023-10-12_03.41.21-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12880902/crash-2023-10-12_03.41.21-server.txt)
[crash-2023-10-12_04.23.46-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12880907/crash-2023-10-12_04.23.46-server.txt)
[crash-2023-10-12_05.05.54-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12880919/crash-2023-10-12_05.05.54-server.txt)
[crash-2023-10-12_05.53.24-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12880936/crash-2023-10-12_05.53.24-server.txt)

At the last minute the game crashed only in the client, I don't know if "Player Companions" has anything to do with it, this is my friend's log:
Client(My friend on the same network) log:
[crash.log](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12881210/crash.log)

**Additional**
I just saw that you updated to version player_companions_1.20.1-6.7.0.
This Friday/Saturday I will test the mod again with this version

Thanks for everything!

**Comment by MarkusBordihn** [comment]
Thanks a lot for the valuable feedback and the additional crash logs.

According the crash log the sound pitch is "null" which should be never the case, because it's a random generated number for all player companions. 🤔
I assume that some of your mods or resource packs change / adjust the sounds which leads to this crashes.

Anyways, I added some additional checks in the code to make sure that none of the sound related values will be used if they are not defined or overwritten by some other mods with an invalid value.

The updated version 6.7.1 should solve all related issues, but please let me know if you still experience any crashes with this version.

Thanks a lot.

**Comment by M25R4PTOR** [comment]
Is version 1.20 compatible with 1.20.1?

**Comment by M25R4PTOR** [comment]
I test player_companions_1.20-6.7.1 in minecraft 1.20.1 and crash with Dobutsu and Small-Slime

**Debugging**
[crash-2023-10-12_21.03.40-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12886603/crash-2023-10-12_21.03.40-server.txt)
[crash-2023-10-12_21.43.23-server.txt](https://github.com/MarkusBordihn/BOs-Player-Companions/files/12886605/crash-2023-10-12_21.43.23-server.txt)

Tomorrow and the next day i will be able to continue testing if you update the version

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. Sorry, that's my fault, I forgot to add `@override` for the standard playSound, so this should be fixed with 6.7.2 and all sounds should now have the additional checks in place.

It could take some time until the new version is online, because of the CurseForge malware scanner which sometimes requires a manually human review which delays the release.

**Comment by M25R4PTOR** [comment]
Perfect, if version 6.7.2 is uploaded tonight in curseforge I will test it.

Is there a way to transfer companions from one world to another?
I tried it with the structure block by putting the player companion item in a chest but in the new world the item shows an error when used.

**Comment by M25R4PTOR** [comment]
This is the first time it has taken so long for the version to appear in curseforge, is this normal? (Tonight I can test)

**Comment by MarkusBordihn** [comment]
Yes this is normal with their latest change. The have a malware scanner in place, when the malware scanner failed for some reason they need a manually human review instead which could take between 1-5 days.

See:
![image](https://github.com/MarkusBordihn/BOs-Player-Companions/assets/12183293/5ecb2f37-1625-4f83-8ada-b9c9af688db2)

Unfortunately there is nothing which I could do from my side to speedup this manually review.

In general it's good that they have something like this in place to make sure no malware is distributed over their network, but it's adds an additional delay for releases especially before/over the weekend.

**Comment by M25R4PTOR** [comment]
No problem, when it appears on the page I will test it.

Is there a way to transfer the companions obtained in one world to another by passing some type of file or with some mod?

Thanks for everything!

**Comment by MarkusBordihn** [comment]
Never tried this myself so far, but basically there are two possibile ways for this.

- You can put the player companion item in a  chest and import the chest into the world. All relevant information are stored in the relevant companion item itself and not in the entity.
- You can use the backup file and the `/player_companions backup load` backup command to restore the companions together with the `/player_companions summon` command to re-spawn the companion in the new world.

![image](https://github.com/MarkusBordihn/BOs-Player-Companions/assets/12183293/db5f4a9b-8029-4354-9008-a0891cb91f25)

The backup files are stored in the world folder under player_companions.

**Comment by M25R4PTOR** [comment]
I have finally been able to test the version and it works perfectly.

If you create a new mod I would like to play it hehehe

Thank you for everything!
