### ISSUE TITLE
Nether crash

### ISSUE THREAD

**Issue by P14S0P** [MarkusBordihn/BOs-Player-Companions#31]
**Describe the bug**
On 1.20.1 when you go to the nether, it gives you a time out, then when you load the world,  you spawn in the nether but when you get out, it gives you a time out again.

**To Reproduce**

1. Go to 'the nether'

**Expected behavior**
Get in the nether... 

**Screenshots**

**Debugging**
Nope, because it is a time out for the server, so it doesnt crash

****
modlist: [Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)
[libIPN (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/libipn)
[FallingTree (Forge&Fabric) (by rakambda)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)
[Snuffles (by schnappdragon)](https://www.curseforge.com/minecraft/mc-mods/snuffles)
[Automatic Tool Swap (by MelanX)](https://www.curseforge.com/minecraft/mc-mods/automatic-tool-swap)
[Atlas Lib (by smileycorp)](https://www.curseforge.com/minecraft/mc-mods/atlas-lib)
[U Team Core (by HyCraftHD)](https://www.curseforge.com/minecraft/mc-mods/u-team-core)
[Trade Cycling (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/trade-cycling)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Useful Backpacks (by HyCraftHD)](https://www.curseforge.com/minecraft/mc-mods/useful-backpacks)
[Inventory Profiles Next (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Enchant Icons (by CountXD)](https://www.curseforge.com/minecraft/texture-packs/enchant-icons-countxd)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Better Invisibility (by Purplicious_Cow_)](https://www.curseforge.com/minecraft/mc-mods/better-invisibility)
[Load My Resources [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/load-my-resources-forge)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Boss Refreshed (by lukidon)](https://www.curseforge.com/minecraft/texture-packs/boss-refreshed)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[No Auto Jump (by Jacky)](https://www.curseforge.com/minecraft/mc-mods/no-auto-jump)
[Combat Roll [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/combat-roll)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Obscure Tooltips (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips)
[Villagers Drop Emeralds on Death (by exlinegames)](https://www.curseforge.com/minecraft/mc-mods/villagers-drop-emeralds-on-death)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
[GroovyModLoader (GML) (by matyrobbrt)](https://www.curseforge.com/minecraft/mc-mods/gml)
[Prism [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/prism-lib)
[Infinite Trading (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/infinite-trading)
[WATERMeDIA: Multimedia API (by SrRapero720)](https://www.curseforge.com/minecraft/mc-mods/watermedia)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Ding (Forge) (by ohaiiChun)](https://www.curseforge.com/minecraft/mc-mods/ding)
[Replanter (by Areuthreateningme)](https://www.curseforge.com/minecraft/mc-mods/replanter)
[DEUF - Duplicate Entity UUID Fix (by CAS_ual_TY)](https://www.curseforge.com/minecraft/mc-mods/deuf-duplicate-entity-uuid-fix)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[Craft the Totem of Undying [FORGE & FABRIC] (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/craft-the-totem-of-undying)
[Bocchium (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/bocchium)
[Paragliders (by Tictim)](https://www.curseforge.com/minecraft/mc-mods/paragliders)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Paintings ++ (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/paintings)
[BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
[WTHIT Forge Edition (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit-forge)
[Configurable Despawn Timer (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/configurable-despawn-timer)
[Rubidium Extra (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Motschen's Better Leaves (by Motschen)](https://www.curseforge.com/minecraft/texture-packs/motschens-better-leaves)
[Tax Free Levels (Fabric/(Neo)Forge) (by Fourmisain)](https://www.curseforge.com/minecraft/mc-mods/tax-free-levels)
[No Telemetry (by kb1000)](https://www.curseforge.com/minecraft/mc-mods/no-telemetry)
[Duckling (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Resource Pack Overrides [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/resource-pack-overrides)
[Item Highlighter [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-highlighter)
[Infinity With Mending (by GoForceX)](https://www.curseforge.com/minecraft/mc-mods/infinity-with-mending)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Zaynen's Craftable Nether Star Mod (by zany_zaynen)](https://www.curseforge.com/minecraft/mc-mods/zaynens-craftable-nether-star)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Pick Up Notifier [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[Simple Discord Rich Presence (Forge / Fabric) (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Enchantment Transfer (Fabric/Forge) (by treekicker4)](https://www.curseforge.com/minecraft/mc-mods/enchantment-transfer)
[Suggestion Provider Fix (by HarleyOConnor)](https://www.curseforge.com/minecraft/mc-mods/suggestion-provider-fix)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[Inventory Totem (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/inventory-totem)
[Ender's Delight (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/enders-delight)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
[TexTrue's Embeddium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-embeddium-options)
[FastChest Reforged (by yGlobalista)](https://www.curseforge.com/minecraft/mc-mods/fastchest-reforged)
[Sky Villages [Forge] (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/sky-villages-forge)
[ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[Respawning Animals [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/respawning-animals)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Tumbleweed (by bconv)](https://www.curseforge.com/minecraft/mc-mods/tumbleweed)
[Actually Unbreaking [Forge] (by wutdahack)](https://www.curseforge.com/minecraft/mc-mods/actually-unbreaking-forge)
[Tiny Item Animations (by Trivaxy)](https://www.curseforge.com/minecraft/mc-mods/tiny-item-animations)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[LittlePictureFrames (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/littleframes)
[Icons (by mr_ch0c0late1)](https://www.curseforge.com/minecraft/texture-packs/icons)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Medieval Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/medieval-music)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Better Respawn (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/better-respawn)
[Bottle Your Xp (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Client Crafting (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/client-crafting)
[Elytra Slot (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)
[[EMF] Entity Model Features [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-model-features)
[Villagers Respawn (Now with FORGE and FABRIC versions) (by MacTso)](https://www.curseforge.com/minecraft/mc-mods/villagers-respawn)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Loot Beams: Relooted! (by shiroroku)](https://www.curseforge.com/minecraft/mc-mods/loot-beams)
[Compact Help Command (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/compact-help-command)
[Falling Leaves (Forge) (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[Traveler's Titles (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/travelers-titles)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Krypton Reforged (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/krypton-reforged)
[Born in Chaos (by mongoose_artist)](https://www.curseforge.com/minecraft/mc-mods/born-in-chaos)
[Simple Hats (by fonnymunkey)](https://www.curseforge.com/minecraft/mc-mods/simplehats)
[Enderman Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/enderman-overhaul)
[Hourglass (by DuckyCrayfish)](https://www.curseforge.com/minecraft/mc-mods/hourglass)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Cull Leaves (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/cull-leaves)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[TPA (by were_fox)](https://www.curseforge.com/minecraft/mc-mods/tpa)
[Healing Bed (by noxgame1230)](https://www.curseforge.com/minecraft/mc-mods/healing-bed)
[Starter Kit (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
[Craftable Horse Armour & Saddle [CHA&S] (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/cha-s)
[Signpost (by Gollorum)](https://www.curseforge.com/minecraft/mc-mods/signpost)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Better Animations Collection (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/better-animations-collection)
[Item Borders [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-borders)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Sleep Time (by noxgame1230)](https://www.curseforge.com/minecraft/mc-mods/sleep-time)
[Durability Tooltip (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/durability-tooltip)
[Why stacks of 16? (by LaidBackSloth)](https://www.curseforge.com/minecraft/mc-mods/why-stacks-of-16)
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[Not Enough Recipe Book [NERB] (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook)
[Responsive Shields (by Revvilo)](https://www.curseforge.com/minecraft/mc-mods/responsive-shields)
[Log Begone (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/log-begone)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Bed Benefits (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bed-benefits)
[Model Gap Fix (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[JeremySeq's Damage Indicator (by JeremySeq)](https://www.curseforge.com/minecraft/mc-mods/jeremyseq-damage-indicator)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Eating Animation [Forge] (by matyrobbrt)](https://www.curseforge.com/minecraft/mc-mods/eating-animation-forge)
[MiniMePets (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/minimepets)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Better Safe Bed (by frankv_)](https://www.curseforge.com/minecraft/mc-mods/better-safe-bed)
[NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Fantasy's Furniture (by ApexModder)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture)
[Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[Auto Third Person (by quat)](https://www.curseforge.com/minecraft/mc-mods/auto-third-person)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Craftable Saddles (by alexdaum1)](https://www.curseforge.com/minecraft/mc-mods/craftable-saddles)
[Charm of Undying (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/charm-of-undying)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Better Ping Display (by Quintinity)](https://www.curseforge.com/minecraft/mc-mods/better-ping-display)
[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[Sildur's Vibrant shaders (by SildurFX)](https://www.curseforge.com/minecraft/shaders/sildurs-vibrant-shaders)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Complementary Shaders - Reimagined (by EminGTR)](https://www.curseforge.com/minecraft/shaders/complementary-reimagined)
[Gaming Deco (by PlayTics)](https://www.curseforge.com/minecraft/mc-mods/gaming-deco)
[Showcase Item (by Ultramegaaa)](https://www.curseforge.com/minecraft/mc-mods/showcase-item)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[Obscure API (Forge) (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/obscure-api)
[Extra Zombie Drops (by OnMod)](https://www.curseforge.com/minecraft/mc-mods/extra-zombie-drops)
[AlwaysEat (by suppergerrie2)](https://www.curseforge.com/minecraft/mc-mods/alwayseat)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Ash API (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/ash-api)
[Recipe Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric)
[Chat Notify (by NotRyken)](https://www.curseforge.com/minecraft/mc-mods/chat-notify)
[Friendly Fire (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/friendly-fire)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Icon Xaero's (by godkyo98)](https://www.curseforge.com/minecraft/texture-packs/icon-xaeros)
[Drink Beer Refill (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/drink-beer-refill)
[Medieval Paintings (by The_Great_ZIN)](https://www.curseforge.com/minecraft/mc-mods/medieval-paintings)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Ok Zoomer Forge (by matyrobbrt)](https://www.curseforge.com/minecraft/mc-mods/ok-zoomer-forge)
[Better Golems (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/bettergolem)
[Areas (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/areas)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Paladin's Furniture (by UnlikePaladin)](https://www.curseforge.com/minecraft/mc-mods/paladins-furniture)
[Mythic Mounts (Forge) (by chirpycricket__)](https://www.curseforge.com/minecraft/mc-mods/mythic-mounts-forge)
[Clean Swing Through Grass (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/clean-swing-through-grass)
[Borderless Window (by nekeras)](https://www.curseforge.com/minecraft/mc-mods/borderless)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Clear Despawn [Forge] (by StrikerRocker)](https://www.curseforge.com/minecraft/mc-mods/clear-despawn)
[Aquamirae (Forge) (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/ob-aquamirae)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Open Parties and Claims (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims)
[Village Bell Recipe (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/village-bell-recipe)
[Tips (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tips)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Better Burning (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/better-burning)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[More Dragon Eggs (by Darkere)](https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs)
[Game Menu Remove GFARB (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/game-menu-remove-gfarb)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Random Village Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/random-village-names)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Plushie Mod (by Link4real)](https://www.curseforge.com/minecraft/mc-mods/plushie-mod)
[Benched (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/benched)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Loading Backgrounds - Oceans (by lupiiin_)](https://www.curseforge.com/minecraft/texture-packs/loading-backgrounds-oceans)
[Loading Backgrounds (by lupiiin_)](https://www.curseforge.com/minecraft/mc-mods/loading-backgrounds)
[Name Tag Tweaks (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/name-tag-tweaks)
[Creeper no Break Blocks (by Talilon)](https://www.curseforge.com/minecraft/mc-mods/creeper-no-break-blocks)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Fast Paintings (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/fast-paintings)
[[1.20.1] OpenStairs (by HookerHeels)](https://www.curseforge.com/minecraft/mc-mods/openstairs)
[Chimes (by BlewberryPie)](https://www.curseforge.com/minecraft/mc-mods/chimes)
[Realm RPG: Dragon Wyrms (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-dragon-wyrms)
[ApexCore (by ApexModder)](https://www.curseforge.com/minecraft/mc-mods/apexcore)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Redirector [Modern] (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/redirectionor)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Display Case (by ChappiePie)](https://www.curseforge.com/minecraft/mc-mods/displaycase)
[You Died (by GoryMoon)](https://www.curseforge.com/minecraft/mc-mods/you-died)
[Stack Refill (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/stack-refill)
[Daily Rewards (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/daily-rewards)
[Blinking Ender Eyes (by Futureazoo)](https://www.curseforge.com/minecraft/texture-packs/blinking-ender-eyes)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Enhanced Boss Bars (by Nakuring)](https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars)
[Caged Mobs (by Corgam)](https://www.curseforge.com/minecraft/mc-mods/caged-mobs)
[Achievements Optimizer (by big_energy)](https://www.curseforge.com/minecraft/mc-mods/achievements-optimizer)
[Visuality: Reforged (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/visuality-reforged)
[Traveler's Backpack (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack)
[DespawnTweaker (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/despawntweaker)

**Additional context**

**Comment by MarkusBordihn** [comment]
Could you please let me know the exact version of the mod you are using ?
I released yesterday an updated version 6.10.0 which includes a fix for the described error.
If would be great if you could confirm if you could reproduce the issue with version 6.10.0 or if you only see this error with version 6.9.0 or so. Thanks.

**Comment by P14S0P** [comment]
I don't remember the version since i deleted the mod from the modpack 2 days ago, im uploading the modpack and i need to wait a couple days for the review and stuff, after that im gonna try to add the mod again and i'll be in touch.

**Comment by MarkusBordihn** [comment]
Ok thanks for the feedback. When you removed the mod from the modpack two days ago then it was the "older" / "broken"  version.
