### ISSUE TITLE
Add translation file for Spanish (Spain).

### ISSUE THREAD

**Issue by Arkathus** [MarkusBordihn/BOs-Player-Companions#32]
I have created a translation of the mod into Spanish (Spain), which is my native language, to play more comfortably. I would like to share it with others.

[es_es.json](https://github.com/MarkusBordihn/BOs-Player-Companions/files/14387959/es_es.json)

**Comment by MarkusBordihn** [comment]
Thanks for the translation file. Could you please create a pull request for this.
See: https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Basically you need to perform the following steps:

1. Use https://github.com/MarkusBordihn/BOs-Player-Companions/fork to create a fork.
2. Inside your fork, add your translation file to `src/main/resources/assets/player_companions/lang`
3. Create a pull request over `Pull requests` -> `New Pull request` and select your fork.

All of these could be done directly in the browser and not requires and IDE or special text editor.

Thanks. ;)

**Comment by Arkathus** [comment]
I think it's already done, I apologize if it's not; honestly, I'm new to this platform.

**Comment by Arkathus** [comment]
Okay, I've done it the way you told me. I think it should be fine now.
