### ISSUE TITLE
Blue Fairy/Fairies Disappears After Taming

### ISSUE THREAD

**Issue by Coraline77447** [MarkusBordihn/BOs-Player-Companions#5]
Minecraft: 1.18.1
Forge: 39.1.2
Player Companions: 0.9.1

**Describe the bug**
When I tried to tame a blue fairy she disappears in survival mode but not in creative mode, I've tried taming multiple blue fairies in survival mode and all of them vanished after I tamed them in survival mode, the last blue fairy that I've found in CWG I decided to tame her in creative mode. After I gave her two taming cakes her corresponding item plopped right into my inventory like how it should've in the first place with the first blue fairy that I've tamed...

**To Reproduce**
1. Start a test world in survival mode with cheats enabled
2. Then bring in the blue fairy spawn egg and spawn in some blue fairies and the taming cake (with/without cookies)
3. And then try to tame at least one of them if you've spawned in multiple blue fairies
4. When you successfully tame one she should vanish into thin air while you're in survival mode, NOT creative mode

**Expected behavior**
After taming a blue fairy in survival mode her corresponding item should plop right into the inventory in one of the hotbar slots. 

**Screenshots**
N/A

**Debugging**
[latest.log](https://github.com/MarkusBordihn/BOs-Player-Companions/files/8493146/latest.log)

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
N/A

**Additional context**
Apon creating this issue report I'm still playing on CWG (Cora World Guns) right now. 
Last time I've successfully tamed a blue fairy was  most likely before mod version 0.9.0. As of 0.9.1.
I'm no longer able to successfully tame a blue fairy in survival mode after 0.9.0, in the latest log (still not finished writing since the game is still running right now) at/near the bottom it says that I spawned in a blue fairy companion item because I don't want a blue fairy with a male name since a fairy is female not male which is weird and strange for a female character to be named Charlie or any other male name...........
I originally would've *decided to cheat and spawn one in by grabbing a blue fairy companion item instead of continuing to try to tame a natural wild blue fairy when she'll just vanish like the others.................
*I would've said to myself "fuck this I'm gonna take the fuck it all pill and spawn one in myself already tamed instead of endlessly searching for one only to experience the exact same thing happen over, over, over, over, and over again since apparently taming a bluw fairy in survival mode is completely bugged/broken....."

**Comment by MarkusBordihn** [comment]
Thanks a lot for the detailed report. Unfortunately I see nothing strange in the logs, besides that Minecraft is not really finding your player profile, but I assume that this is an offline server or so.

I have adjusted something in version 0.9.2 to make sure that the item is dropped in the case it could not be stored in the player inventory (excluding creative mode). Let me know if this fixed your issue.

The name "Charlie" itself is a neutral name and is used for both female and males, there are a lot of references which using this name even for female faires. I added some additional names to have a better mix of names.

Besides of this you have always the options to change the name with a name tag, if you got a name you don't like.

**Comment by Coraline77447** [comment]
"Thanks a lot for the detailed report. Unfortunately I see nothing strange in the logs, besides that Minecraft is not really finding your player profile, but I assume that this is an offline server or so."

Why the logs keeps saying that it's having trouble authenticating my profile is cause I'm using a third party launcher (Tlauncher) for modded minecraft.
I do have the official launcher BUT....
The thing with the official launcher is that it has more background processes than TLauncher does and I know that I can't force stop any of those extra background processes or else the game could crash or worse so I'm still using Tlauncher for modded minecraft since it only has one background process running in the background and the last time I've tried to suse the official launcher for modded minecraft that it  just kept crashing the game and I seriously do not want to waste any more of my play time (play sessions) trying to debug my mods lists every time I try to use the offical launcher and it's unoptimized along with way too many background processes eating away at my pc resources (RAM mostly) anyways....

BTW I wish that I cloud include screenshots of the issue but sometimes this issue happens rarely, especially with the Welsh Corgi but after 0.9.0 it's happening often with the blue fairy. Maybe I could try to capture before and after screenshots of the issue with the blue fairy but not today unfortunately since I'm planning on making a brand new 1.18.2 world dedicated to A.O.A 3 (Nevermine) which has been ported to 1.18.2 but in Public Alpha since it's going through major changes like the skills system has beem changed along with the latest public alpha release removing some stuff that was previously in the mod but not anymore.
The last time I've played A.O.A was in 1.16.5 and I've moved on from 1.16.5 when 1.18 came along after 1.17.1.
Already have a mod list set up for 1.18.2 but was just missing one of the major mods (A.O.A, Tinkers' Construct and Twilight Forest)
When I come back to either Cora Tinkers' (C.T) (1.18.1) or Cora World Guns (C.W.G) (1.18.1) which has Player Companions I'll try to take screenshots before and after I try to tame a blue fairy in survival mode, not in creative and not in dev environment (I don't have access to that anyways....) when I try out 0.9.2 to see if one oc the changes has fixed the issue.

Also I know that what I've said in my issue report regarding names for the companions that I was just stating my opinion about that since a woman irl could potentially be named a boys name like Charlie but it's unusual for a woman to have a boys name tho. 
Sure I could of just used a nametag to change it's name and changed it's item name from a boys name to a girls name but the thing about the companion item is that the companion's original data remains untouched by the anvil and the mod still calls out the original name, not the new name for the companion...
I keep "telling" my fairies who had names that I didn't want that that's not their name anymore even tho they can't actually hear me which I'm pretending to tell them that what the mod calls them ain't their original name anymore.

**Comment by MarkusBordihn** [comment]
The latest version include the option to adjust the list of names over the config file.
So you are free to remove or add any name your want for your different kind of companions.

At the moment I'm using the basic vanilla function to give the player companion item to the player, but if you see still issues with the latest version 1.0.1 I could try to do this manually and to confirm if the item is in the inventory.
