### ISSUE TITLE
How do I replace the name of the companion with commands?

### ISSUE THREAD

**Issue by m00t01** [MarkusBordihn/BOs-Player-Companions#8]
I'm trynna use it with twitchspawn, for whenever people follow me, they give me a random minion and I spawn it and it appears with their name, but the spawn item (tamed) appears as ex. "Jhon23" but when I spawn it with right click it appears with a random predefined name and I don't want that.

I tried using the customname nbt but only works with untamed ones and spawn eggs, but I wont have time to tame them with twitch spawn where the chat can spawn me sh!t that I could die of

**Comment by MarkusBordihn** [comment]
Thanks for the feedback, interesting use-case. 
Just to understand you correctly, because I never used twitch-spawn myself.

* You want that companions items (automatically tamed on your first use), has an option to pre-define the name and/or to change it over an simple command ?
* Ideal they should take the name from twitchspawn automatically.

It would be great if you could provide a screenshot / part of the stream how the item appears first with "Jhon23" over  twitchspawn before you spawn it. Thanks.

**Comment by MarkusBordihn** [comment]
Relevant Mod: https://www.curseforge.com/minecraft/mc-mods/twitchspawn

**Comment by m00t01** [comment]
> Thanks for the feedback, interesting use-case. Just to understand you correctly, because I never used twitch-spawn myself.
> 
> * You want that companions items (automatically tamed on your first use), has an option to pre-define the name and/or to change it over an simple command ?
> * Ideal they should take the name from twitchspawn automatically.
> 
> It would be great if you could provide a screenshot / part of the stream how the item appears first with "Jhon23" over twitchspawn before you spawn it. Thanks.

Yes, I can represent it with images:
TwitchSpawn can automatically drop you named items, its like the game uses the CustomName NBT tag on the gifted item on itself, like passing it on an anvil before droping it to you
![image](https://user-images.githubusercontent.com/108951614/180331838-abd325af-9bcf-47ec-a591-ceab406b24ce.png)

But when I use the custom named ite, the minion doesn't appear with the custom name I gave him with the anvil (nor wit the custom name NBT nor the TwitchSpawn's CustomName Command)
![image](https://user-images.githubusercontent.com/108951614/180331943-1e9924a4-507d-431c-9c24-ce917ce1f23a.png)

So I would love that you make it that when you custom name the item your companion automatically appears with the name you gave him on the anvil, so that problem would be solved.

With that also should happen that if I give him a custom skin it doesn't override the name cuz they are different nameslol
![image](https://user-images.githubusercontent.com/108951614/180332099-3d2384d3-b043-43b3-80ba-a95e87c8b556.png)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the details. I added a fix which should help with this
